- hosts: localhost
  tasks:
    - name: Tag a resource with multiple tags
      aws_tagging:
        resource: "resource"
        region: "us-east-1"
        tags: "{'imanewkey': 'imanewvalue', 'imanewkey2' : 'imanewvalue2'}"