- hosts: localhost
  tasks:
    - name: Tag an ec2 with multiple tags
      aws_tagging:
        resource: "arn:aws:ec2:us-east-1:ACCT_ID:instance/i-ID"
        region: "us-east-1"
        tags:
          - key: "imakey"
            value: "imavalue"
            key: "another_tag"
            value: "1"