- hosts: localhost
  tasks:
    - name: Tag a resource with a single tag
      aws_tagging:
        resource: "first-test-trampoline-test-ansible4"
        region: "us-east-1"
        tags: "{'imanewkey': 'imanewvalue'}"